import torch
import struct
import numpy as np
import os
import sys

from tokenizer import KiboTokenizer
from model import KiboMicroLM

def export_int8_indonesian():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    vocab_json_path = os.path.join(base_dir, "kibo_vocab.json")
    
    tok = KiboTokenizer()
    tok.load(vocab_json_path)
    vocab_size = len(tok.tok_to_id)
    
    model = KiboMicroLM(vocab_size=vocab_size, n_embd=192, n_head=4, n_layer=4, max_seq_len=128)
    model_path = os.path.join(base_dir, "kibo_model_id.pt")
    if not os.path.exists(model_path):
        print(f"File model {model_path} tidak ditemukan. Silakan jalankan train_id.py terlebih dahulu.")
        return
        
    model.load_state_dict(torch.load(model_path, map_location="cpu"))
    model.eval()
    
    bin_path = os.path.join(base_dir, "kibo_model_int8.bin")
    
    with open(bin_path, 'wb') as f:
        named_params = list(model.named_parameters())
        num_tensors = len(named_params)
        
        # Header: Magic 0x4B49424F = 'KIBO'
        header = struct.pack('iiiiiii', 0x4B49424F, vocab_size, 192, 4, 4, 128, num_tensors)
        f.write(header)
        
        total_int8_bytes = 0
        total_fp32_bytes = 0
        
        for name, param in named_params:
            name_bytes = name.encode('utf-8')
            f.write(struct.pack('i', len(name_bytes)))
            f.write(name_bytes)
            
            data = param.detach().numpy()
            num_elements = data.size
            
            if "weight" in name and data.ndim == 2:
                max_val = float(abs(data).max())
                scale = max_val / 127.0 if max_val > 0 else 1.0
                q_data = (data / scale).round().clip(-128, 127).astype('int8')
                
                f.write(struct.pack('ifi', 1, scale, num_elements))
                f.write(q_data.tobytes())
                total_int8_bytes += num_elements
            else:
                f.write(struct.pack('ifi', 0, 1.0, num_elements))
                f.write(data.astype('float32').tobytes())
                total_fp32_bytes += num_elements * 4
                
    file_size_kb = os.path.getsize(bin_path) / 1024
    print(f"✅ Export INT8 Sukses: {bin_path} ({file_size_kb:.1f} KB)")
    
    # Export C++ Header
    header_path = os.path.join(base_dir, "kibo_vocab.h")
    with open(header_path, 'w', encoding='utf-8') as f:
        f.write("// Autogenerated Vocabulary Header for Kibo Indonesian Edition\n")
        f.write("#pragma once\n\n")
        f.write(f"#define KIBO_VOCAB_SIZE {vocab_size}\n")
        f.write("#define KIBO_N_EMBD 192\n")
        f.write("#define KIBO_N_HEAD 4\n")
        f.write("#define KIBO_N_LAYER 4\n")
        f.write("#define KIBO_MAX_SEQ_LEN 128\n")
        f.write(f"#define KIBO_EOS_ID {tok.tok_to_id.get('<EOS>', 3)}\n\n")
        
        f.write("static const char* const KIBO_SPECIAL_TOKENS[] = {\n")
        for st in tok.special_tokens:
            esc = st.replace('\\', '\\\\').replace('"', '\\"')
            f.write(f'  "{esc}",\n')
        f.write("};\n")
        f.write(f"#define KIBO_NUM_SPECIAL_TOKENS {len(tok.special_tokens)}\n\n")
        
        f.write("static const char* const KIBO_VOCAB_TABLE[KIBO_VOCAB_SIZE] = {\n")
        for i in range(vocab_size):
            token_str = tok.id_to_tok[i]
            esc = token_str.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t')
            f.write(f'  "{esc}", // {i}\n')
        f.write("};\n")
        
    print(f"✅ Header C++ Dihasilkan: {header_path}\n")

if __name__ == "__main__":
    export_int8_indonesian()
