[env:esp32s3_espidf]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
build_flags = 
    -DCONFIG_SPIRAM_MODE_OCT=1
    -DCONFIG_ESP32S3_COPROC_SUPPORT=1
    -O3
