import torch
import struct
import json
import os
import sys

sys.path.append("/home/aiot/Projects/SBC/kibo_microlm")
from tokenizer import KiboTokenizer
from model import KiboMicroLM

def export_int8_model():
    print("==========================================")
    print("   Exporting Kibo INT8 Model for ESP32    ")
    print("==========================================")
    
    tok = KiboTokenizer()
    tok.load("/home/aiot/Projects/SBC/kibo_microlm/kibo_vocab.json")
    vocab_size = len(tok.tok_to_id)
    
    model = KiboMicroLM(vocab_size=vocab_size, n_embd=192, n_head=4, n_layer=4, max_seq_len=128)
    model_path = "/home/aiot/Projects/SBC/kibo_microlm/kibo_model_2mb.pt"
    model.load_state_dict(torch.load(model_path, map_location="cpu"))
    model.eval()
    
    bin_path = "/home/aiot/Projects/SBC/kibo_microlm/kibo_model_int8.bin"
    
    # 1. Generate Binary File for Flash/PSRAM
    # Binary Format:
    # Header (7 int32s = 28 bytes):
    #   [Magic: 0x4B49424F ("KIBO"), vocab_size, n_embd (192), n_head (4), n_layer (4), max_seq_len (128), num_tensors]
    # For each tensor:
    #   [name_len (int32), name_chars, is_quantized (int32: 1=int8, 0=float32), scale (float32), num_elements (int32), data (int8 bytes or float32 bytes)]
    
    with open(bin_path, 'wb') as f:
        named_params = list(model.named_parameters())
        num_tensors = len(named_params)
        
        # Magic 0x4B49424F = 'KIBO'
        header = struct.pack('iiiiiii', 0x4B49424F, vocab_size, 192, 4, 4, 128, num_tensors)
        f.write(header)
        
        total_int8_bytes = 0
        total_fp32_bytes = 0
        
        for name, param in named_params:
            name_bytes = name.encode('utf-8')
            f.write(struct.pack('i', len(name_bytes)))
            f.write(name_bytes)
            
            data = param.detach().numpy()
            num_elements = data.size
            
            # Quantize 2D weight matrices to INT8; keep 1D LayerNorm/Biases in FP32
            if "weight" in name and data.ndim == 2:
                max_val = float(abs(data).max())
                scale = max_val / 127.0 if max_val > 0 else 1.0
                q_data = (data / scale).round().clip(-128, 127).astype('int8')
                
                f.write(struct.pack('ifi', 1, scale, num_elements))
                f.write(q_data.tobytes())
                total_int8_bytes += num_elements
            else:
                # Store biases / LayerNorms in FP32
                f.write(struct.pack('ifi', 0, 1.0, num_elements))
                f.write(data.astype('float32').tobytes())
                total_fp32_bytes += num_elements * 4
                
    file_size_kb = os.path.getsize(bin_path) / 1024
    file_size_mb = file_size_kb / 1024
    print(f"✅ INT8 EXPORT SUCCESS: {bin_path}")
    print(f"File Size: {file_size_mb:.2f} MB ({file_size_kb:.1f} KB)")
    print(f"Total INT8 Weights: {total_int8_bytes:,} bytes")
    print(f"Total FP32 Biases/Norms: {total_fp32_bytes:,} bytes")
    
    # 2. Export C++ Header for Vocab
    header_path = "/home/aiot/Projects/SBC/kibo_microlm/kibo_vocab.h"
    with open(header_path, 'w', encoding='utf-8') as f:
        f.write("// Autogenerated Vocabulary for Kibo Micro-LM\n")
        f.write("#pragma once\n\n")
        f.write(f"#define KIBO_VOCAB_SIZE {vocab_size}\n")
        f.write("#define KIBO_N_EMBD 192\n")
        f.write("#define KIBO_N_HEAD 4\n")
        f.write("#define KIBO_N_LAYER 4\n")
        f.write("#define KIBO_MAX_SEQ_LEN 128\n")
        f.write(f"#define KIBO_EOS_ID {tok.tok_to_id.get('<EOS>', 3)}\n\n")
        
        # Special Tokens array
        f.write("static const char* const KIBO_SPECIAL_TOKENS[] = {\n")
        for st in tok.special_tokens:
            esc = st.replace('\\', '\\\\').replace('"', '\\"')
            f.write(f'  "{esc}",\n')
        f.write("};\n")
        f.write(f"#define KIBO_NUM_SPECIAL_TOKENS {len(tok.special_tokens)}\n\n")
        
        # Vocab array
        f.write("static const char* const KIBO_VOCAB_TABLE[KIBO_VOCAB_SIZE] = {\n")
        for i in range(vocab_size):
            token_str = tok.id_to_tok[i]
            # Escape strings for C++
            esc = token_str.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '\\r').replace('\t', '\\t')
            f.write(f'  "{esc}", // {i}\n')
        f.write("};\n")
        
    print(f"✅ Generated C++ Header: {header_path}\n")

if __name__ == "__main__":
    export_int8_model()
