// Autogenerated Vocabulary for Kibo Micro-LM
#pragma once

#define KIBO_VOCAB_SIZE 89
#define KIBO_N_EMBD 192
#define KIBO_N_HEAD 4
#define KIBO_N_LAYER 4
#define KIBO_MAX_SEQ_LEN 128
#define KIBO_EOS_ID 3

static const char* const KIBO_SPECIAL_TOKENS[] = {
  "<PAD>",
  "<UNK>",
  "<BOS>",
  "<EOS>",
  "User:",
  "Kibo:",
  "[HAPPY]",
  "[LAUGH]",
  "[CRYING]",
  "[SLEEPY]",
  "[LOVE]",
  "[ANGRY]",
  "[DIZZY]",
  "[VAMPIRE]",
  "[NEUTRAL]",
  "[CAT]",
};
#define KIBO_NUM_SPECIAL_TOKENS 16

static const char* const KIBO_VOCAB_TABLE[KIBO_VOCAB_SIZE] = {
  "<PAD>", // 0
  "<UNK>", // 1
  "<BOS>", // 2
  "<EOS>", // 3
  "User:", // 4
  "Kibo:", // 5
  "[HAPPY]", // 6
  "[LAUGH]", // 7
  "[CRYING]", // 8
  "[SLEEPY]", // 9
  "[LOVE]", // 10
  "[ANGRY]", // 11
  "[DIZZY]", // 12
  "[VAMPIRE]", // 13
  "[NEUTRAL]", // 14
  "[CAT]", // 15
  "\n", // 16
  " ", // 17
  "!", // 18
  "%", // 19
  "*", // 20
  "+", // 21
  ",", // 22
  "-", // 23
  ".", // 24
  "/", // 25
  "0", // 26
  "1", // 27
  "2", // 28
  "3", // 29
  "4", // 30
  "5", // 31
  "6", // 32
  "7", // 33
  "8", // 34
  "9", // 35
  ":", // 36
  "<", // 37
  ">", // 38
  "?", // 39
  "A", // 40
  "B", // 41
  "C", // 42
  "D", // 43
  "E", // 44
  "G", // 45
  "H", // 46
  "I", // 47
  "J", // 48
  "K", // 49
  "L", // 50
  "M", // 51
  "N", // 52
  "O", // 53
  "P", // 54
  "R", // 55
  "S", // 56
  "T", // 57
  "U", // 58
  "V", // 59
  "W", // 60
  "Y", // 61
  "Z", // 62
  "[", // 63
  "]", // 64
  "a", // 65
  "b", // 66
  "c", // 67
  "d", // 68
  "e", // 69
  "f", // 70
  "g", // 71
  "h", // 72
  "i", // 73
  "j", // 74
  "k", // 75
  "l", // 76
  "m", // 77
  "n", // 78
  "o", // 79
  "p", // 80
  "r", // 81
  "s", // 82
  "t", // 83
  "u", // 84
  "v", // 85
  "w", // 86
  "y", // 87
  "z", // 88
};
